services:
  - type: web
    name: lottery-api
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn res:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CURL_CFFI_CA_BUNDLE
        value: /etc/ssl/certs/ca-certificates.crt

